language: java
install: true

os: linux
dist: trusty
jdk: 
  - openjdk12
  - openjdk11

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "build/libs/migrator.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true